######################################################################
# Automatically generated by qmake (3.0) Tue Apr 5 22:55:10 2016
######################################################################

QT += testlib
CONFIG += C++11
QMAKE_CXX = clang++
QMAKE_CC = clang
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += TestFilePool.hh \
           TestZippedBuffer.hh \
           TestZippedBufferPool.hh \
           TestZipper.hh \
           ../FilePool.hh \
           ../ZippedBuffer.hh \
           ../ZippedBufferPool.hh \
           ../Zipper.hh
SOURCES += mainTest.cpp \
           TestFilePool.cpp \
           TestZippedBuffer.cpp \
           TestZippedBufferPool.cpp \
           TestZipper.cpp \
           ../FilePool.cpp \
           ../ZippedBuffer.cpp \
           ../ZippedBufferPool.cpp \
           ../Zipper.cpp
