######################################################################
# Automatically generated by qmake (3.0) Sat Jun 18 15:20:00 2016
######################################################################

QT += testlib
CONFIG += C++11
QMAKE_CXX = clang++
QMAKE_CC = clang
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += TestEpsiFileCompressor.hh \
           TestFilePool.hh \
           TestWritter.hh \
           TestZippedBuffer.hh \
           TestZippedBufferPool.hh \
           TestZipper.hh \
           ../EpsiFileCompressor.hh \
           ../FilePool.hh \
           ../Writter.hh \
           ../ZippedBuffer.hh \
           ../ZippedBufferPool.hh \
           ../Zipper.hh
SOURCES += mainTest.cpp \
           TestEpsiFileCompressor.cpp \
           TestFilePool.cpp \
           TestWritter.cpp \
           TestZippedBuffer.cpp \
           TestZippedBufferPool.cpp \
           TestZipper.cpp \
           ../EpsiFileCompressor.cpp \
           ../FilePool.cpp \
           ../Writter.cpp \
           ../ZippedBuffer.cpp \
           ../ZippedBufferPool.cpp \
           ../Zipper.cpp
