######################################################################
# Automatically generated by qmake (3.0) Tue Apr 5 20:35:58 2016
######################################################################

QT += testlib
CONFIG += C++11
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

QMAKE_CXX = clang++
QMAKE_CC = clang

# Input
HEADERS += TestFilePool.hh \
           TestZippedBuffer.hh \
           TestZippedBufferPool.hh \
           ../FilePool.hh \
           ../ZippedBuffer.hh \
           ../ZippedBufferPool.hh
SOURCES += mainTest.cpp \
           TestFilePool.cpp \
           TestZippedBuffer.cpp \
           TestZippedBufferPool.cpp \
           ../FilePool.cpp \
           ../ZippedBuffer.cpp \
           ../ZippedBufferPool.cpp
